channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=24.0
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.0
  - numpy==1.25.2
  - psutil==5.9.5
  - scikit-learn==1.3.1
  - scipy==1.11.3
name: mlflow-env
